/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.veldergard.engine;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EngineLibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        EngineLibrary classUnderTest = new EngineLibrary();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
